### ISSUE TITLE
Redirecting serial connection to a virtual port

### ISSUE THREAD

**Issue by grassjelly** [Wiz-IO/platform-wizio#1]
Hi!
First of all thank you for this great library. 

Just wondering is it possible to redirect the serial connection to a virtual port? I'd like to run a Python script that talks to the simulated hardware through serial comm. 

Maybe I missed it, but I didn't see any option to define which port I can pipe the console to or this is something not available yet?

Thanks in advance! :)

**Comment by LaBus3** [comment]
Use a null modem emulator like com0com(windows) or tty0tty(linux)

**Comment by grassjelly** [comment]
thanks
