### ISSUE TITLE
[Build Error] error: '_pCloseServer' was not declared in this scope

### ISSUE THREAD

**Issue by uc-class-roy** [Wiz-IO/platform-wizio#2]
Upon running build in platformio, build error occurred.

Verbose mode can be enabled via `-v, --verbose` option
?[32m<<<<<<<<<<<< WIZIO ARDUINO SIMULATOR ( WINDOWS ) 2019 Georgi Angelov >>>>>>>>>>>>
CONFIGURATION: https://docs.platformio.org/page/boards/wizio/windows.html
PLATFORM: WizIO 1.0.3 #19b3fe0 > WizIO Arduino Simulator ( WINDOWS )
HARDWARE: 100MHz, 3.81MB RAM, 3.81MB Flash
DEBUG: Current (uart) On-board (uart)
PACKAGES: framework-wizio be60a5b
LDF: Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 6 compatible libraries
Scanning dependencies...
No dependencies
Building in release mode
Compiling .pio\build\windows\src\main.cpp.o
Compiling .pio\build\windows\_arduino\IPAddress.cpp.o
Compiling .pio\build\windows\_arduino\Print.cpp.o
Compiling .pio\build\windows\_arduino\Stream.cpp.o
Compiling .pio\build\windows\_arduino\WMath.cpp.o
Compiling .pio\build\windows\_arduino\WString.cpp.o
Compiling .pio\build\windows\_arduino\cbuf.cpp.o
Compiling .pio\build\windows\_arduino\dtostrf.c.o
Compiling .pio\build\windows\_arduino\new.cpp.o
Compiling .pio\build\windows\_arduino\no_std.c.o
Compiling .pio\build\windows\_arduino\wiring_pulse.c.o
Compiling .pio\build\windows\_arduino\wiring_shift.c.o
Compiling .pio\build\windows\_core\EthernetClient.cpp.o
Archiving .pio\build\windows\lib_arduino.a
Compiling .pio\build\windows\_core\HardwareSerial.cpp.o
Compiling .pio\build\windows\_core\arduino_main.cpp.o
C:\Users\RaveStrikeR\.platformio\packages\framework-wizio\arduino\cores\windows\EthernetClient.cpp: In constructor 'EthernetClient::EthernetClient()':
C:\Users\RaveStrikeR\.platformio\packages\framework-wizio\arduino\cores\windows\EthernetClient.cpp:33:2: error: '_pCloseServer' was not declared in this scope
C:\Users\RaveStrikeR\.platformio\packages\framework-wizio\arduino\cores\windows\EthernetClient.cpp: In constructor 'EthernetClient::EthernetClient(uint8_t)':
C:\Users\RaveStrikeR\.platformio\packages\framework-wizio\arduino\cores\windows\EthernetClient.cpp:39:2: error: '_pCloseServer' was not declared in this scope
C:\Users\RaveStrikeR\.platformio\packages\framework-wizio\arduino\cores\windows\EthernetClient.cpp: In member function 'virtual void EthernetClient::stop()':
C:\Users\RaveStrikeR\.platformio\packages\framework-wizio\arduino\cores\windows\EthernetClient.cpp:230:6: error: '_pCloseServer' was not declared
in this scope
Indexing .pio\build\windows\lib_arduino.a
*** [.pio\build\windows\_core\EthernetClient.cpp.o] Error 1

platform.ini
[env:windows]
platform = wizio
board = windows
framework = arduino

**Comment by porlock** [comment]
same problem for me :( it seemsthat author abandon this project, 
@uc-class-roy  any luck ?
